Application Layer --|> Presentation Layer: Data
Presentation Layer --|> Session Layer: Session
Session Layer --|> Transport Layer: Segments
Transport Layer --|> Network Layer: Packets
Network Layer --|> Data Link Layer: Frames
Data Link Layer --|> Physical Layer: Bits