pie_chart: {
  title: "Land Division"
  slices: [
    {value: 5 label: "5 acres" fill: "red"},
    {value: 5 label: "5 acres" fill: "orange"},
    {value: 5 label: "5 acres" fill: "yellow"},
    {value: 5 label: "5 acres" fill: "green"},
    {value: 5 label: "5 acres" fill: "blue"},
    {value: 5 label: "5 acres" fill: "purple"}
  ]
}